### ISSUE TITLE
Add Community Meeting section to Contributing document

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1075]
We currently don't mention the community meetings on:
https://github.com/googleforgames/agones/blob/master/CONTRIBUTING.md

We should:

- [ ] Make a mention of it
- [ ] Link to a calendar
- [ ] Link to a list of past recordings.

**Comment by markmandel** [comment]
@thisisnotapril this seems up your alley :smile: if you don't have a moment to make a PR, if you have the info at hand, happy to do the PR for you.

**Comment by thisisnotapril** [comment]
@markmandel Can we take this as an opportunity to move the assorted community/contrib documentation to the agones/community repo? Then I can push to master and PR with all the branches I want! 😈

**Comment by roberthbailey** [comment]
https://github.com/googleforgames/agones-community is looking awfully empty....

To make your proposal more concrete, it seems like the files that would move are https://github.com/googleforgames/agones/blob/master/docs/governance/community_membership.md and https://github.com/googleforgames/agones/blob/master/docs/governance/templates/membership.md. Is there anything else that you would move over?

**Comment by markmandel** [comment]
Sounds like a good opportunity to move things, sure -- I guess who has approval to approve things over there? Since all meta operations will now likely occur over there, yes?

**Comment by roberthbailey** [comment]
Strawman: agones approvers should be the initial set of approvers for agones-community.

**Comment by markmandel** [comment]
> Strawman: agones approvers should be the initial set of approvers for agones-community.

Makes sense to me.
