### ISSUE TITLE
Request Releaser role for Agones Repository

### ISSUE THREAD

**Issue by sawagh** [googleforgames/agones#2115]
### GitHub Username
sawagh

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../CONTRIBUTING.md)
- [ ] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @markmandel 

### List of contributions to the Agones project
- PRs reviewed / authored
- Issues responded to

**Comment by roberthbailey** [comment]
+1

**Comment by markmandel** [comment]
👍🏻 from me!

**Comment by roberthbailey** [comment]
I've granted you the access needed for cutting releases. Onward ho!
