### ISSUE TITLE
Release Automation: Determine if we can stop using milestones for releases

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2455]
**Is your feature request related to a problem? Please describe.**
Right now there are a number of steps in the [release process](https://github.com/googleforgames/agones/blob/main/docs/governance/templates/release_issue.md) related to milestone management:

- [ ] Review [closed issues with no milestone](https://github.com/googleforgames/agones/issues?q=is%3Aissue+is%3Aclosed+no%3Amilestone++-label%3Ainvalid+-label%3Aduplicate+-label%3Aquestion+-label%3Awontfix++-label%3Aarea%2Fmeta) and add relevant ones to the current milestone.
- [ ] Review closed issues in the current milestone to ensure that they have appropriate tags.
- [ ] Review [merged PRs that have no milestone](https://github.com/googleforgames/agones/pulls?q=is%3Apr+is%3Amerged+no%3Amilestone+) and add them to the current milestone.
- [ ] Review merged PRs in the current milestone to ensure that they have appropriate tags.
- [ ] Ensure the next version milestone is created.
- [ ] Any issues in the current milestone that are not closed, move to next milestone.
- [ ] If full release, close the current milestone. *Congratulations!* - the release is now complete! :tada: :clap: :smile: :+1:

**Describe the solution you'd like**
Determine if we can stop using milestones for releases. We are not using milestones for work planning and they may not be necessary to generate release notes. If we stop using them, then we can remove a number of steps from the release process.

**Comment by markmandel** [comment]
If the new changelog generation from github is not milestone dependent, I think we can drop this requirement entirely.
