### ISSUE TITLE
GameServer Fleets

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#70]
# Design

## Description
Fleets are a group of warm servers that are available to be allocated to players when needed.

In Kubernetes parlance, they are the `Deployment`/`ReplicaSet` to Pods, but for `GameServer`s

## Features

- Be able to define a `Fleet`, with an attached `GameServerTemplate` (much like a `PodTemplate`)
- The Fleet ensures there is always `replicas` number of Healthy `GameServers` available (assuming resources exist)
- If a `GameServer` becomes Unhealthy, then delete it and create it anew (we may add more options at a later date).
- If you delete a `Fleet`, this also deletes the backing `GameServers` (this should be by default in Kubernetes now anyway)
- A mechanism (TBD) to be able to get an `allocated` GameServer out of the pool.
  - If a warm server is not available, then a cold one should be started (assuming resources)
  - An allocated `GameServer` is moved to a `Allocated` state on allocation.
- If the `replicas` are increased in the `Fleet`, the number of `GameServers` is increased to match that number (assuming resources)
 - If the `replicas` are decreased in the `Fleet`, the number of `GameServers` is decreased to match that number.
    - `GameServers` that are in an `Allocated` state will never be deleted during the decrease
- The `GameServer` `template` is changed, then we will mimic a `Deployment` in that we can do either a `Recreate` or a `RollingUpdate` to switch out the waiting warm servers.
  - GameServers that are in an Allocated state will never be deleted during the decrease
- Validation of the configuration and changes.

# Configuration
```yaml
apiVersion: "stable.agon.io/v1alpha1"
kind: Fleet
metadata:
  name: "fleet-example"
spec:
  # number of GameServers
  replicas: 10
  # deployment strategy for updating the image
  # Lifted directly from https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#deploymentstrategy-v1-apps
  strategy:
    # Recreate or RollingUpdate. Default to RollingUpdate
    type: RollingUpdate
    rollingUpdateDeployment: # optional rolling update config
      maxSurge: "25%"
      maxUnavailable: "25%"
  # A GameServer template
  template:
    # Standard ObjectMeta
    metadata:
      labels:
        mylabel: myvalue
    # GameServer spec
    spec:
      containerPort: 7654
        template:
          spec:
            containers:
            - name: cpp-simple
              image: gcr.io/agon-images/cpp-simple-server:0.1
```
## Allocation

Allocation is done through creating a `FleetAllocation` record via kubectl or the API.

For example:

```yaml
apiVersion: "stable.agon.io/v1alpha1"
kind: FleetAllocation
metadata:
  name: "sample-allocation"
spec:
  fleetName: "fleet-example"
```
The returned value from creating a `GameServerAllocation` has the details of the allocated server (And moves the `GameServer` to the state `Allocated`.)

For example:

```yaml
apiVersion: "stable.agon.io/v1alpha1"
kind: FleetAllocation
metadata:
  name: "sample-allocation"
spec:
  fleetName: "fleet-example"
status:
  gameserver:
    metadata:
      name: "allocated-game-server"
    spec:
      containerPort: 7654
      template:
        spec:
          containers:
          - name: cpp-simple
            image: gcr.io/agones-images/cpp-simple-server:0.1
    status:
      address: 192.168.99.100
      nodeName: agones
      port: 7373
      state: Allocated
```
- Allocations can only be created, the only way to remove an allocation (at this stage) is to delete the backing GameServer.

# Work Breakdown

- [x] GameServerSet (The `GameServerSet` to `Fleet` as `ReplicaSet` to `Deployment`) (#156)
- [x] Creating a `Fleet` creates a `GameServerSet` (#174)
- [x] Create an `Allocation` from a fleet (#193)
- [x] `Recreate` update strategy (#199)
- [ ] `Rolling` update strategy

# Out of scope
- Pre-caching of images. We'll see how testing works without this for now.

# Research
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#replicaset-v1-apps
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#deployment-v1-apps
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/webhook.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/certs.go

**Comment by markmandel** [comment]
Currently working on `GameserverSets` (the `Fleet` version of `ReplicaSets`) on my [fork over here](https://github.com/markmandel/agones/tree/feature/gameserverset). Will finalise, and then submit for PR before doing the Fleet work that overlays this work.

**Comment by justinliew** [comment]
I'm very interested in this, as we never did our "fleets" using Kubernetes APIs. Rather, we had a separate service that monitored our pods and did our warming up, scaling up and down, and what not. At the time I wasn't as familiar with K8s as I am now, so I may have come up with something closer to your approach if I did it again.

**Comment by markmandel** [comment]
Start of "Creating a Fleet creates a GameServerSet" first PR has started [over in this repository and branch](https://github.com/markmandel/agones/tree/feature/fleet-no-update)

**Comment by markmandel** [comment]
Fleet Allocation work started [over here](https://github.com/markmandel/agones/tree/feature/fleet-allocation)

**Comment by markmandel** [comment]
Work on doing a straight replace when updating Fleet's GameServer details, can be found over here:
https://github.com/markmandel/agones/tree/feature/fleet-replace

**Comment by markmandel** [comment]
Rolling update strategy work is here:
https://github.com/markmandel/agones/tree/feature/fleet-rolling
